repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1  # Use the desired version of clang-format
    hooks:
      - id: clang-format
        name: Clang Format with Restage
        entry: bash -c '
          CLANG_DIR=Drivers/Embedded-Base;
          FILES=$(git diff --cached --name-only --diff-filter=ACMRT | grep -E "\.(c|cpp|h|hpp)$");
          if [ -n "$FILES" ]; then
            clang-format --style=file --config ${CLANG_DIR}/.clang-format --ignore=${CLANG_DIR}/.clang-ignore -i $FILES;
            git add $FILES;
          fi'
        language: system
        types: [python]
        pass_filenames: false
