name: cerberus

services:
    ner-gcc-arm:
        image: ghcr.io/northeastern-electric-racing/embedded-base:dyn-ody
        build: .
        network_mode: host
        privileged: true
        volumes:
            - type: bind
              source: .
              target: /home/app
            - type: bind
              source: /dev
              target: /dev
        tty: true
        expose:
            - "3240"
        environment:
            - DEBUG_PORT=/dev/ttyACM0
            - STM_TARGET_NAME=stm32f4
            - USBIP_PORT=1-1.3
            - PROJECT_NAME=Cerberus
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        
