version: "3.7"
services:
  workspace:
    build:
      context: .
    volumes:
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    image: nwdepatie/ner-gcc-arm:latest
    stdin_open: true
    tty: true
    privileged: true