version: "3.7"
services:
  workspace:
    image: nwdepatie/ner-gcc-arm:latest
    stdin_open: true
    tty: true
    volumes:
        - type: bind
          source: /dev/ttyACM0
          target: /dev/ttyACM0
